### ISSUE TITLE
#11 Проверка времени и даты логина

### ISSUE THREAD

**Issue by mansurmabo** [ESDP-15-3/student-crm#11]
# Мотивация
Нужно проверить кто и во сколько залогинелся в систему
# Описание
Нужна проверка периода входа.
Если в данный период есть занятие у группы, то отображем список студентов
Иначе редиректим на рут или делаем render plain c любым сообщением (это временно по идее редирект в Кабинет препода)
Предаварительно в фикстурах установить периоды занятий если это необходимо.
# Критерии приемки
Допустим *Логинемся в период занятий* 
Если *Поялвется список студентов*  
Допустим *Логинемся в неурочное время* 
Если *сработал редирект*  
То *все ок*
# Оценочное время на решение задачи
2 ч.ч.

**Comment by Tamaramun** [comment]
Кабинеты для пользователей не созданы, поэтому проверка времени и даты логина не требуется.
