### ISSUE TITLE
#14 Создать чекбокс "выбрать все"

### ISSUE THREAD

**Issue by mansurmabo** [ESDP-15-3/student-crm#14]
# Мотивация
Создать чекбокс "выбрать все"
# Описание
Чекбокс должен находиться в колонке над всеми остальными чекбоксами

# Критерии приемки
Допустим *открываем страницу посещаемости* 
Если *кликаем на чекбокс(выбрать все)*  
То *выделяются все чекбоксы*
# Оценочное время на решение задачи
0.5 ч.ч.

**Comment by Tamaramun** [comment]
Данный функционал перестал быть нужным.
