### ISSUE TITLE
#16 Создать пометку(коммент) для студентов посетивших занятие с другой группой

### ISSUE THREAD

**Issue by mansurmabo** [ESDP-15-3/student-crm#16]
# Мотивация
Я как пользователь с ролью преподавателя желаю чтоб у студентов посетивших занятия не со своей группой была пометка.
# Описание
Создать доп поле для отображение комментариев для студента посетившие занятие не в свое время. Поле с комментарием должно быть скрытым, но с каким-нибудь флажком при наведение или при клике должно разворачиваться с текстом коммента  
# Критерии приемки
Допустим *"Иванова" пришел с другой группой пропустив время своего занятия* 
Если *Препод отмечает его присутвие в его группе но при этом должен заполнить поле коммента* 
То *При последующем открытии списка посещаемости данного урока появляется флажок напротив имени "Иванова"*
Допустим *Кликнуть на этот флажок*
Если *Появляется коммент*
То *Все ок*
# Оценочное время на решение задачи
1 ч.ч.

**Comment by Tamaramun** [comment]
Время отметки студента не играет роли, поэтому данный функционал не требует выполнения.
