### ISSUE TITLE
Создать модель "Educational Unit" и связать с "Course Elements"

### ISSUE THREAD

**Issue by KnyazNiyaz** [ESDP-15-3/student-crm#22]
# Мотивация

Для определения к какому учебному блоку принадлежат элементы курса,

# Описание

Создать модель "Educational Unit" с одним единственным полем "name" и установить связь (one to many) с моделью "Элементы курса.
Добавить фикстуры для моделей "Course Elements", "Periods", "Educational Unit".

# Критерии приемки

**Допустим** у меня открыт Rubymine, 
**Если** я открою Схему зависимости STUDENT-CRM,
**То** я увижу, что появилась модель Educational Unit с полем Name
**И** связанная one to many с Periods.

**Comment by Tamaramun** [comment]
0.5 часа
