### ISSUE TITLE
Создать функционал  отметки и отображения студентов.

### ISSUE THREAD

**Issue by KnyazNiyaz** [ESDP-15-3/student-crm#24]
# Мотивация
Для проверки на текущий элемент курса

# Описание
Необходимо отобразить отмеченных студентов в таблице с чекбоксами
Создать функционал отметки присутствующих студентов при клике на чекбокс

# Критерии приемки 

** Сценарий проверки отображения отмеченных студентов **
**Допустим**  я на главной странице сайта,
**Если** я пройду на страницу посещений студентов,
**То**  я должен увидеть отмеченных студентов в таблице.

** Сценарий отметки студентов**
**Допустим** я на странице посещений студентов,
**Если** отмечу, что Иванов Иван присутствует,
**То** в модели Attendances, должна появиться запись о присутствии И. Ивана.

**Comment by Tamaramun** [comment]
Потрачено 4 часа.
