### ISSUE TITLE
Проверка на текущий элемент курса

### ISSUE THREAD

**Issue by KnyazNiyaz** [ESDP-15-3/student-crm#25]
# Мотивация 
Для определения текущего учебного блока

# Описание 
Отметка может может производиться только за текущий и предыдущие элемента курса.
Если период элемента курса и текущее время совпадают, то Учитель может отметить столбец, который должен быть подсвеченным(активный). При не совпадении периода, то ни один столбец из будущих элементов курса не должен быть активен.

# Критерии приемки
**Сценарий отметки при совпадении периода элемента курса с текущим временем**
**Допустим** я на странице посещений,
**Если**  отмечу присутствие И.Ивана  лишь в подсвеченном столбце элемента курса
**То**  данные о присутствии И.Ивана должны быть в модели Attendances

**Сценарий отметки при не совпадении периода с будущими элемента курса с текущим временем**
**Допустим** я на странице посещений,
**Если** отмечу присутствие И.Ивана,
**То** данные о присутствии И.Ивана не должны попасть модель Attendances(disabled)

Необходимое время для решении задачи:
2ч

**Comment by mansurmabo** [comment]
2 hour spend time
