### ISSUE TITLE
Показ всех учебных блоков

### ISSUE THREAD

**Issue by KnyazNiyaz** [ESDP-15-3/student-crm#28]
# Мотивация 
Для вывода посещений за текущий и прошедшие учебные блоки.

# Описание
Необходимо вытащить посещаемости элементов курса Group №1 за прошедшие учебные блоки через разделитель.
# Критерии приемки

**Допустим** я на странице посещений студентов Group №1 за текущий учебный блок,
**Если** я нажму на кнопку "Все учебные блоки",
**То** я должен увидеть посещаемость студентов Group № 1 за текущий и прошедшие учебные блоки по вертикали через разделитель.

Оценочное время:
3ч.

**Comment by Tamaramun** [comment]
Spent time:  4 hours
