### ISSUE TITLE
Рефакторинг отображения страницы

### ISSUE THREAD

**Issue by Tamaramun** [ESDP-15-3/student-crm#34]
# Мотивация
Я, как пользователь, хочу понимать на какой странице нахожусь по заголовку и цвету кнопки, определяющей учебный блок.

# Описание
Заголовок, показывающий местоположения пользователя должен располагаться в самом верху после navbar, и выглядеть так: "Ведомость посещаемости <название группы> <название курса>". Убрать названия учебных блоков с вьюшки.  Изменить цвета кнопок "текущий", "предыдущий", "все"; изначально все кнопки серые ("btn btn-default"), но активная кнопка синяя ("btn btn-primary"). Перенести кнопки в layout.

# Критерии приемки
**Сценарий**
**Допустим**, я хочу посмотреть ведомость посещаемости студентов  первой группы Ruby.
**Если** я открою страницу посещаемости студентов за текущий учебный блок,
**То** я под заголовок под navbar большими буквами "Ведомость посещаемости студентов группы 1 Ruby on Rails". Кнопка "текущий" будет синяя. Выведется текущий ученый блок без названия. 

# Оценочное время
1 часа

**Comment by KnyazNiyaz** [comment]
Потрачено: 1 час
