### ISSUE TITLE
Выведение периодов по учебному блоку

### ISSUE THREAD

**Issue by Tamaramun** [ESDP-15-3/student-crm#45]
# Мотивация
Я, как пользователь, хочу видеть даты занятий, которые относятся к одному курсу, группе, учебному блоку, в таблице в хронологическом порядке.
# Описание
Даты занятий в таблице, то есть, периоды, выводятся по id, равным id элементов курса, а должны находиться по ним.

**Comment by mansurmabo** [comment]
Spend time 1h
