### ISSUE TITLE
Авторизация пользователей

### ISSUE THREAD

**Issue by mansurmabo** [ESDP-15-3/student-crm#48]
# Проблема 
Нужно сделать авторизацию пользователей системы по ролям. 
# Решение
Для того чтобы сделать авторизацию пользователей, необходимо переделать Модель Students в модель Users с ролями (Admin Teacher Student Guest)
для удобства можно испольщовать гем cancancan.
# Оценочное время 
2h

**Comment by Tamaramun** [comment]
Потрачено 3 часа

**Comment by Tamaramun** [comment]
На проверку ролей пользователя и изменения их распределения потрачено 2 часа
