### ISSUE TITLE
Cоздание студента

### ISSUE THREAD

**Issue by KnyazNiyaz** [ESDP-15-3/student-crm#49]
# Мотивация
Для добавления нового студента в БД

# Описание
Необходимо создать функционал создания студента

# Критерии приемки
**Сценарий**
**Допустим** я на странице localhost:3000/users и хочу добавить И.Ивана
**Если** я кликну на кнопку "Создать студента"
**И** введу все необходимые данные
**То** в списке студентов должен появиться И.Иван

**Оценочное время** 
6ч

**Comment by mansurmabo** [comment]
Functional added 
Spend time 2h
