### ISSUE TITLE
Просмотр студентов

### ISSUE THREAD

**Issue by KnyazNiyaz** [ESDP-15-3/student-crm#50]
# Мотивация
Показ всех  учащихся студентов по фильтру 

# Описание
Необходимо создать функционал для просмотра данных  учащихся студентов по группе и курсу

# Критерии приемки 
**Сценарий** Отображения данных учащихся студентов
**Допустим** я на странице "localhost:3000/users" 
**Если** я выберу студентов 2 группы по курсу РУБИ
**То** я  должен увидеть студентов по выше выбранной категории

**Оценочное время**
6ч

**Comment by mansurmabo** [comment]
Functional added 
Spend time 1h
