### ISSUE TITLE
Редактирование студента

### ISSUE THREAD

**Issue by KnyazNiyaz** [ESDP-15-3/student-crm#51]
# Мотивация
Изменение данных студента в БД

# Описание
Необходимо создать редактирования информации о студенте.

# Критерии приемки 
**Допустим** я на странице' localhost:3000/users'
**Если** я кликну на кнопку редактирования студента И.Ивана
**И** отредактирую имя на Степана
**То** в списке студентов он должен отображаться, как Иванов Степан

**Оценочное время**
6ч

**Comment by mansurmabo** [comment]
Functional added 
Spend time 1h

**Comment by KnyazNiyaz** [comment]
2 часа
