### ISSUE TITLE
Удаление студента

### ISSUE THREAD

**Issue by KnyazNiyaz** [ESDP-15-3/student-crm#52]
# Мотивация
Удаление всей информации студента из БД
# Описание
Удаление данных об определенном студенте

# Критерии приемки
**Допустим** я на странице 'localhost:3000/users'
**Если** я кликну на кнопку удаления студента И.Ивана
**То** в списке студентов не должно быть студента с именем И.Иван

**Оценочное время**
6 ч

**Comment by mansurmabo** [comment]
Functional added 
Spend time 1h
