### ISSUE TITLE
Просмотр студента

### ISSUE THREAD

**Issue by KnyazNiyaz** [ESDP-15-3/student-crm#53]
# Мотивация
Для просмотра всей информации о студенте

# Описание
Необходимо сделать функционал просмотра студента

# Критерии приемки
**Сценарий**
**Допустим** я на странице "localhost:3000/users"
**Если** выберу студента Иванова Ивана 
**То** я должен увидеть всю информацию об И.Иване

**Оценочное время**
6ч

**Comment by mansurmabo** [comment]
Functional added 
Spend time 1h
