### ISSUE TITLE
Функционал для распечатки договора

### ISSUE THREAD

**Issue by KnyazNiyaz** [ESDP-15-3/student-crm#58]
# Мотивация 
Я как администратор системы хочу сразу после введения нового студента в базу заключить с ним договор

# Описание 
Необходимо создать функционал для распечатки шаблонного договора. После создания студента, должна появиться функция "Распечатать", которая автоматически введет данные студента в договор(PDF-формат) и распечатает через принтер. Также должна быть возможность внесения изменения в договор.  

# Критерии приемки
**Сценарий**
**Допустим** Я только что создать студента
**Если** я кликну на кнопку "Распечатать" 
**То** необходимые данные студента должны автоматически ввестись в правильные поля и распечататься через принтер  

**Оценочное время**
8ч

**Comment by mansurmabo** [comment]
Потрачено на функционал 10 ч.
