### ISSUE TITLE
Создание тестов для CRUD курсов

### ISSUE THREAD

**Issue by Tamaramun** [ESDP-15-3/student-crm#69]
Тесты к тикету #64

# Критерии приемки
**Сценарий**
**Допустим** я залогиненный пользователь.
**Если** я зайду на страницу '/courses'
**То** я увижу список всех существующих курсов.

**Сценарий** я на странице всех курсов.
**Допустим** я выбираю "Создать новый курс" .
**Если** я напишу в поле названия курса Ruby,
**То** я увижу этот курс в списке всех курсов.

**Допустим** я выбираю "Редактировать" .
**Если** я изменю название курса Ruby на HTML,
**То** я в списке всех курсов тоже появится HTML.

**Допустим** я выбираю "Удалить" .
**Если** это будет Ruby,
**То** этот курс исчезнет из списка всех курсов.

**Допустим** я нажимаю на название курса.
**Если** это HTML,
**То** я увижу учебный план занятий этого курса.

# Оценочное время
5 часов

**Comment by KnyazNiyaz** [comment]
3

**Comment by KnyazNiyaz** [comment]
3 часа
