### ISSUE TITLE
#7 Checkbox - JS

### ISSUE THREAD

**Issue by mansurmabo** [ESDP-15-3/student-crm#7]
# Мотивация
Узнать как работать с чекбоксами с помощью JS 
# Описание
Сохранение студента в БД после отметки чекбокса с помощью JS
# Критерии приемки
Допустим *отмечаем чекбокс* 
Если *данные сохранены в бд* 
То *все ок!*
# Оценочное время на решение задачи
60 мин

**Comment by Tamaramun** [comment]
Used Ajax,
Were helped by tutor.

wasted time: 1 hour
