### ISSUE TITLE
Создание тестов для CRUD группы

### ISSUE THREAD

**Issue by Tamaramun** [ESDP-15-3/student-crm#70]
Тесты к тикету #65 

# Критерии приемки
**Сценарий**
**Допустим** я залогиненный пользователь.
**Если** я зайду на страницу '/groups'
**То** я увижу список всех существующих групп.

**Сценарий** я на странице всех групп.
**Допустим** я выбираю "Создать группу" .
**Если** я напишу в поле названия "Группа 1", курс Ruby,
**То** я увижу эту группу в списке всех групп.

**Допустим** я выбираю "Редактировать" .
**Если** я изменю название группы на "Группа 4",
**То** я в списке всех групп тоже вместо Группа 1 появится Группа 4.

**Допустим** я выбираю "Удалить" .
**Если** это будет Группа 1,
**То** эта группа исчезнет из списка всех групп.

**Допустим** я нажимаю на название группы.
**Если** это Группа 1,
**То** я увижу название этой группы, название курса, к которому она относится, и список студентов этой группы..

# Оценочное время
5 часов

**Comment by KnyazNiyaz** [comment]
3 часа
