### ISSUE TITLE
Исправление багов.

### ISSUE THREAD

**Issue by Aziz0026** [ESDP-15-3/student-crm#75]
# Мотивация
Нужно исправить ошибки которые появляються при работе системы.
# Описание
При добавления курс елемента есть проблема с роутами. 
При удаление студента, остаються его посещения.
# Критерии приемки
Надо исправить эти ошибки, и чтоб система работала без ошибок.
# Оценочное время на решение задачи
1 ч.ч.

**Comment by Aziz0026** [comment]
# Мотивация
Нужно исправить ошибки которые появляються при работе системы.
# Описание
При добавления курс елемента есть проблема с роутами. 
При удаление студента, остаються его посещения.
# Критерии приемки
Надо исправить эти ошибки, и чтоб система работала без ошибок.
# Оценочное время на решение задачи
1 ч.ч.

**Comment by Tamaramun** [comment]
Потрачен 1 час.
