### ISSUE TITLE
Оправка пароля пользователю на Email

### ISSUE THREAD

**Issue by mansurmabo** [ESDP-15-3/student-crm#85]
# Мотивация
Для конфеденциальности данных пользователя при создании необходимо отправлять пароли в письме с сылкой на редактирование.
# Описание
Необходимо убрать поля паролей в форме создание пользователя, отправлять пароль на Email
# Критерии приемки
**Допустим**
Пользователь находиться на странице "создании студента"
**Если**
При заполнении всех обязательных полей жмет кнопку 'Сохранить'
**То**
Создается Юзер с сгенерированным паролем, пароль отправляется на почту указанной в поле Email
# Оценочное время на решение задачи
8 ч.ч.

**Comment by Tamaramun** [comment]
Потрачено 8 часов.
