### ISSUE TITLE
Создание модуля домашка(Преподавтельская часть)

### ISSUE THREAD

**Issue by mansurmabo** [ESDP-15-3/student-crm#87]
# Мотивация
Я как препод должен иметь возможность просматривать, загружать, ставить оценки для ДЗ студентов которые отправили свои домашки
# Описание 
Необходимо создать функционал для скачивания архивов с готовыми ДЗ, создать поле для оценки домашек студента.
# Оценочное 
10 ч.ч.

**Comment by Tamaramun** [comment]
Потрачено 15 часов.
