### ISSUE TITLE
Наладить связь группы с дополнительной домашней работой

### ISSUE THREAD

**Issue by Aziz0026** [ESDP-15-3/student-crm#92]
# Как работает сейчас?
При загрузке дополнительной домашней работы в базу данных не сохраняется id группы.

# Как должно работать?
В таблице дополнительных домашних заданий поле group_id должно содержать id группы текущего студента.

# Как починить?
При загрузке дополнительной домашней работы передать в базу данных id группы, в которой находится текущий студент.

# Оценочное время 
0,5 ч.ч

**Comment by Tamaramun** [comment]
Потрачено 2 часа. Коммит содержит изменения для тикетов #93 #94 #95
